[package]
name = "qingke-rt"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
documentation.workspace = true
homepage.workspace = true
categories.workspace = true
license.workspace = true
description = "Minimal runtime / startup for WCH's RISC-V MCUs, managed by the ch32-rs team"
keywords = ["qingke", "wch", "riscv", "ch32v"]
readme = "README.md"
build = "build.rs"

[features]
default = ["v2a"]
v2a = ["qingke/v2a"]
v2c = ["qingke/v2c"]
v3a = ["qingke/v3a"]
v3b = ["qingke/v3b"]
v3f = ["qingke/v3f"]
v4a = ["qingke/v4a"]
v4b = ["qingke/v4b"]
v4c = ["qingke/v4c"]
v4f = ["qingke/v4f"]
v4j = ["qingke/v4j"]
v5f = ["qingke/v5f"]

u-mode = []
highcode = []

[dependencies]
qingke-rt-macros = { version = "0.8.0", path = "./macros" }
qingke = { version = "0.8.0", path = "../", features = ["critical-section-impl"] }

[package.metadata.docs.rs]
targets = ["riscv32imc-unknown-none-elf"]
